
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: project_ssh_development

# test:
#   <<: *default
#   database: project_ssh_test

# production:
#   <<: *default
#   database: project_ssh_production
#   username: 
#   password: 
